# Generated by Django 6.0.7 on 2026-07-27 13:33

import django.db.models.deletion
from django.db import migrations, models


def migrate_inventory(apps, schema_editor):
    Inventory = apps.get_model("inventory", "Inventory")
    ProductVariant = apps.get_model("products", "ProductVariant")

    for record in Inventory.objects.exclude(product_variant_id=None):
        variant = ProductVariant.objects.filter(id=record.product_variant_id).first()
        if not variant:
            continue

        record.product_id = variant.product_id
        record.save(update_fields=["product_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("products", "0006_remove_product_variant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory",
            options={"verbose_name_plural": "Inventories"},
        ),
        migrations.RemoveConstraint(
            model_name="inventory",
            name="unique_active_inventory_warehouse_variant",
        ),
        migrations.AddField(
            model_name="inventory",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventories",
                to="products.product",
            ),
        ),
        migrations.RunPython(
            migrate_inventory,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="product_variant",
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("warehouse", "product"),
                name="unique_active_inventory_warehouse_product",
            ),
        ),
    ]
