# Generated by Django 6.0.7 on 2026-07-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_variant'),
        ('products', '0008_restore_product_variant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='unique_active_inventory_warehouse_product',
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='products.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('product_variant__isnull', False)), fields=('warehouse', 'product_variant'), name='unique_active_inventory_warehouse_variant'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('product__isnull', False), ('product_variant__isnull', True)), fields=('warehouse', 'product'), name='unique_active_inventory_warehouse_product'),
        ),
    ]
