# Generated by Django 6.0.7 on 2026-07-27 13:33

import django.db.models.deletion
from django.db import migrations, models


def migrate_cart_items(apps, schema_editor):
    CartItem = apps.get_model("carts", "CartItem")
    CartItemAttributeSelection = apps.get_model(
        "carts",
        "CartItemAttributeSelection",
    )
    ProductVariant = apps.get_model("products", "ProductVariant")
    VariantAttributeValue = apps.get_model("products", "VariantAttributeValue")

    for item in CartItem.objects.exclude(product_variant_id=None):
        variant = ProductVariant.objects.filter(id=item.product_variant_id).first()
        if not variant:
            continue

        item.product_id = variant.product_id
        value_ids = list(
            VariantAttributeValue.objects.filter(variant_id=variant.id).values_list(
                "attribute_value_id",
                flat=True,
            )
        )
        item.selection_key = "-".join(str(value_id) for value_id in sorted(value_ids))
        item.save(update_fields=["product_id", "selection_key"])

        for value_id in value_ids:
            CartItemAttributeSelection.objects.get_or_create(
                cart_item_id=item.id,
                attribute_value_id=value_id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
        ("products", "0006_remove_product_variant"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItemAttributeSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_cart_item_variant",
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="carts_carti_cart_id_8cc239_idx",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cart_items",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="selection_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="cartitemattributeselection",
            name="attribute_value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cart_item_selections",
                to="products.attributevalue",
            ),
        ),
        migrations.AddField(
            model_name="cartitemattributeselection",
            name="cart_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute_selections",
                to="carts.cartitem",
            ),
        ),
        migrations.RunPython(
            migrate_cart_items,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product_variant",
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "product"],
                name="carts_carti_cart_id_8f3e40_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product", "selection_key"),
                name="unique_cart_item_product_selection",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitemattributeselection",
            constraint=models.UniqueConstraint(
                fields=("cart_item", "attribute_value"),
                name="unique_cart_item_attribute_value",
            ),
        ),
    ]
