# Generated by Django 6.0.7 on 2026-07-27 13:33

import django.db.models.deletion
from django.db import migrations, models


def migrate_order_items(apps, schema_editor):
    OrderItem = apps.get_model("orders", "OrderItem")
    ProductVariant = apps.get_model("products", "ProductVariant")
    VariantAttributeValue = apps.get_model("products", "VariantAttributeValue")
    AttributeValue = apps.get_model("products", "AttributeValue")

    for item in OrderItem.objects.exclude(product_variant_id=None):
        variant = ProductVariant.objects.filter(id=item.product_variant_id).first()
        if not variant:
            continue

        item.product_id = variant.product_id
        selected_options = {}
        AttributeValue = apps.get_model("products", "AttributeValue")
        for assignment in VariantAttributeValue.objects.filter(variant_id=variant.id):
            attribute_value = AttributeValue.objects.select_related("attribute").get(
                id=assignment.attribute_value_id,
            )
            selected_options[attribute_value.attribute.name] = attribute_value.id

        item.selected_options = selected_options
        item.save(update_fields=["product_id", "selected_options"])


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0006_remove_product_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="selected_options",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(
            migrate_order_items,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product_variant",
        ),
    ]
