# Generated by Django 6.0.7 on 2026-07-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wishlistitem',
            new_name='wishlist_wi_wishlis_5b886d_idx',
            old_name='wishlist_wi_wishlist_idx',
        ),
    ]
