# Generated by Django 6.0.7 on 2026-07-27 13:33

import django.db.models.deletion
from django.db import migrations, models


def migrate_wishlist_items(apps, schema_editor):
    WishlistItem = apps.get_model("wishlist", "WishlistItem")
    ProductVariant = apps.get_model("products", "ProductVariant")

    for item in WishlistItem.objects.exclude(product_variant_id=None):
        variant = ProductVariant.objects.filter(id=item.product_variant_id).first()
        if not variant:
            continue

        item.product_id = variant.product_id
        item.save(update_fields=["product_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_product_variant"),
        ("wishlist", "0002_rename_wishlist_wi_wishlist_idx_wishlist_wi_wishlis_5b886d_idx"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="wishlistitem",
            name="unique_wishlist_item_variant",
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wishlist_items",
                to="products.product",
            ),
        ),
        migrations.RunPython(
            migrate_wishlist_items,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="wishlistitem",
            name="product_variant",
        ),
        migrations.AddConstraint(
            model_name="wishlistitem",
            constraint=models.UniqueConstraint(
                fields=("wishlist", "product"),
                name="unique_wishlist_item_product",
            ),
        ),
    ]
