# Generated by Django 6.0.7 on 2026-07-25 16:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shipment',
            new_name='shipping_sh_order_i_a287c9_idx',
            old_name='shipping_sh_order_i_idx',
        ),
        migrations.RenameIndex(
            model_name='shipment',
            new_name='shipping_sh_status_8a7968_idx',
            old_name='shipping_sh_status_idx',
        ),
        migrations.RenameIndex(
            model_name='shipment',
            new_name='shipping_sh_trackin_af3d4f_idx',
            old_name='shipping_sh_trackin_idx',
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
