# Generated by Django 6.0.7 on 2026-07-27 13:33

import django.db.models.deletion
from django.db import migrations, models


def migrate_shipment_items(apps, schema_editor):
    ShipmentItem = apps.get_model("shipping", "ShipmentItem")
    ProductVariant = apps.get_model("products", "ProductVariant")

    for item in ShipmentItem.objects.exclude(product_variant_id=None):
        variant = ProductVariant.objects.filter(id=item.product_variant_id).first()
        if not variant:
            continue

        item.product_id = variant.product_id
        item.save(update_fields=["product_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_product_variant"),
        (
            "shipping",
            "0002_rename_shipping_sh_order_i_idx_shipping_sh_order_i_a287c9_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipment_items",
                to="products.product",
            ),
        ),
        migrations.RunPython(
            migrate_shipment_items,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="shipmentitem",
            name="product_variant",
        ),
    ]
