# Generated by Django 6.0.7 on 2026-07-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_product_aeb6e3_idx',
            old_name='reviews_re_product__idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_user_id_eeecea_idx',
            old_name='reviews_re_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_status_70a1f9_idx',
            old_name='reviews_re_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewvote',
            new_name='reviews_rev_review__ac542a_idx',
            old_name='reviews_re_review_i_idx',
        ),
    ]
