# Generated by Django 6.0.7 on 2026-07-27 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_reviews(apps, schema_editor):
    Review = apps.get_model("reviews", "Review")
    ProductVariant = apps.get_model("products", "ProductVariant")

    for review in Review.objects.exclude(product_variant_id=None):
        variant = ProductVariant.objects.filter(id=review.product_variant_id).first()
        if not variant:
            continue

        review.product_id = variant.product_id
        review.save(update_fields=["product_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_product_variant"),
        ("products", "0006_remove_product_variant"),
        (
            "reviews",
            "0002_rename_reviews_re_product__idx_reviews_rev_product_aeb6e3_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="unique_active_review_per_user_variant",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="reviews_rev_product_aeb6e3_idx",
        ),
        migrations.AddField(
            model_name="review",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="products.product",
            ),
        ),
        migrations.RunPython(
            migrate_reviews,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="review",
            name="product_variant",
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "-rating"],
                name="reviews_rev_product_2918de_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["approved", "pending"])),
                fields=("user", "product"),
                name="unique_active_review_per_user_product",
            ),
        ),
    ]
