# Generated by Django 6.0.7 on 2026-07-25 16:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_order_i_288dd3_idx',
            old_name='payments_pa_order_i_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_status_21ed42_idx',
            old_name='payments_pa_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_transac_8e9d99_idx',
            old_name='payments_pa_transac_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
