# Generated by Django 6.0.7 on 2026-07-27 13:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def migrate_products_from_variants(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    ProductVariant = apps.get_model("products", "ProductVariant")
    VariantAttributeValue = apps.get_model("products", "VariantAttributeValue")
    ProductAttribute = apps.get_model("products", "ProductAttribute")
    ProductAttributeValue = apps.get_model("products", "ProductAttributeValue")

    for product in Product.objects.all():
        variants = ProductVariant.objects.filter(
            product_id=product.id,
            is_deleted=False,
        ).order_by("-is_default", "id")

        default_variant = variants.first()
        if default_variant:
            product.sku = default_variant.sku
            product.price = default_variant.price
            product.currency = default_variant.currency
        else:
            product.sku = f"PROD-{product.id}"

        product.save(update_fields=["sku", "price", "currency"])

        seen_attributes = set()
        for variant in variants:
            for assignment in VariantAttributeValue.objects.filter(variant_id=variant.id):
                attribute_value = assignment.attribute_value
                attribute_id = attribute_value.attribute_id
                if attribute_id not in seen_attributes:
                    ProductAttribute.objects.get_or_create(
                        product_id=product.id,
                        attribute_id=attribute_id,
                    )
                    seen_attributes.add(attribute_id)

                ProductAttributeValue.objects.get_or_create(
                    product_id=product.id,
                    attribute_value_id=attribute_value.id,
                )


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(default="ETB", max_length=3),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="shop_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="productimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["display_order", "id"]},
        ),
        migrations.AddField(
            model_name="productattribute",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_attributes",
                to="products.attribute",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_attributes",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productattributevalue",
            name="attribute_value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_assignments",
                to="products.attributevalue",
            ),
        ),
        migrations.AddField(
            model_name="productattributevalue",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_attribute_values",
                to="products.product",
            ),
        ),
        migrations.RunPython(
            migrate_products_from_variants,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name="productattribute",
            constraint=models.UniqueConstraint(
                fields=("product", "attribute"),
                name="unique_product_attribute",
            ),
        ),
        migrations.AddConstraint(
            model_name="productattributevalue",
            constraint=models.UniqueConstraint(
                fields=("product", "attribute_value"),
                name="unique_product_attribute_value",
            ),
        ),
    ]
