# Generated by Django 6.0.7 on 2026-07-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_remove_product_variant"),
        ("inventory", "0002_remove_product_variant"),
        ("orders", "0002_remove_product_variant"),
        ("products", "0006_remove_product_variant"),
        ("reviews", "0003_remove_product_variant"),
        ("shipping", "0003_remove_product_variant"),
        ("wishlist", "0003_remove_product_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="variant",
        ),
        migrations.RemoveConstraint(
            model_name="productvariant",
            name="one_active_default_variant",
        ),
        migrations.RemoveConstraint(
            model_name="variantattributevalue",
            name="unique_variant_attribute_value",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="product",
        ),
        migrations.RemoveField(
            model_name="variantattributevalue",
            name="attribute_value",
        ),
        migrations.RemoveField(
            model_name="variantattributevalue",
            name="variant",
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
        migrations.DeleteModel(
            name="VariantAttributeValue",
        ),
    ]
